# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user/v1/user.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rbt.v1alpha1 import options_pb2 as rbt_dot_v1alpha1_dot_options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user/v1/user.proto\x12\x07user.v1\x1a\x1arbt/v1alpha1/options.proto\":\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t:\x04\x82\xb5\x18\x00\"\x0c\n\nGetRequest\";\n\x0bGetResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\":\n\nSetRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"\r\n\x0bSetResponse2\x81\x01\n\x0bUserMethods\x12\x38\n\x03Get\x12\x13.user.v1.GetRequest\x1a\x14.user.v1.GetResponse\"\x06\x82\xb5\x18\x02\n\x00\x12\x38\n\x03Set\x12\x13.user.v1.SetRequest\x1a\x14.user.v1.SetResponse\"\x06\x82\xb5\x18\x02\x12\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user.v1.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._loaded_options = None
  _globals['_USER']._serialized_options = b'\202\265\030\000'
  _globals['_USERMETHODS'].methods_by_name['Get']._loaded_options = None
  _globals['_USERMETHODS'].methods_by_name['Get']._serialized_options = b'\202\265\030\002\n\000'
  _globals['_USERMETHODS'].methods_by_name['Set']._loaded_options = None
  _globals['_USERMETHODS'].methods_by_name['Set']._serialized_options = b'\202\265\030\002\022\000'
  _globals['_USER']._serialized_start=59
  _globals['_USER']._serialized_end=117
  _globals['_GETREQUEST']._serialized_start=119
  _globals['_GETREQUEST']._serialized_end=131
  _globals['_GETRESPONSE']._serialized_start=133
  _globals['_GETRESPONSE']._serialized_end=192
  _globals['_SETREQUEST']._serialized_start=194
  _globals['_SETREQUEST']._serialized_end=252
  _globals['_SETRESPONSE']._serialized_start=254
  _globals['_SETRESPONSE']._serialized_end=267
  _globals['_USERMETHODS']._serialized_start=270
  _globals['_USERMETHODS']._serialized_end=399
# @@protoc_insertion_point(module_scope)
