// @generated by protoc-gen-es v1.3.2 with parameter "target=ts,import_extension=.js"
// @generated from file reactive/v1/reactive.proto (package reactive.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message reactive.v1.A
 */
export class A extends Message<A> {
  /**
   * @generated from field: string a_state = 1;
   */
  aState = "";

  constructor(data?: PartialMessage<A>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "reactive.v1.A";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "a_state", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): A {
    return new A().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): A {
    return new A().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): A {
    return new A().fromJsonString(jsonString, options);
  }

  static equals(a: A | PlainMessage<A> | undefined, b: A | PlainMessage<A> | undefined): boolean {
    return proto3.util.equals(A, a, b);
  }
}

/**
 * @generated from message reactive.v1.B
 */
export class B extends Message<B> {
  /**
   * @generated from field: string b_state = 1;
   */
  bState = "";

  constructor(data?: PartialMessage<B>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "reactive.v1.B";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "b_state", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): B {
    return new B().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): B {
    return new B().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): B {
    return new B().fromJsonString(jsonString, options);
  }

  static equals(a: B | PlainMessage<B> | undefined, b: B | PlainMessage<B> | undefined): boolean {
    return proto3.util.equals(B, a, b);
  }
}

/**
 * @generated from message reactive.v1.C
 */
export class C extends Message<C> {
  /**
   * @generated from field: string c_state = 1;
   */
  cState = "";

  constructor(data?: PartialMessage<C>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "reactive.v1.C";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "c_state", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): C {
    return new C().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): C {
    return new C().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): C {
    return new C().fromJsonString(jsonString, options);
  }

  static equals(a: C | PlainMessage<C> | undefined, b: C | PlainMessage<C> | undefined): boolean {
    return proto3.util.equals(C, a, b);
  }
}

/**
 * @generated from message reactive.v1.GetResponse
 */
export class GetResponse extends Message<GetResponse> {
  /**
   * @generated from field: string combined_response = 1;
   */
  combinedResponse = "";

  constructor(data?: PartialMessage<GetResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "reactive.v1.GetResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "combined_response", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetResponse {
    return new GetResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetResponse {
    return new GetResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetResponse {
    return new GetResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetResponse | PlainMessage<GetResponse> | undefined, b: GetResponse | PlainMessage<GetResponse> | undefined): boolean {
    return proto3.util.equals(GetResponse, a, b);
  }
}

/**
 * @generated from message reactive.v1.UpdateAStateRequest
 */
export class UpdateAStateRequest extends Message<UpdateAStateRequest> {
  /**
   * @generated from field: string a_state = 1;
   */
  aState = "";

  constructor(data?: PartialMessage<UpdateAStateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "reactive.v1.UpdateAStateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "a_state", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateAStateRequest {
    return new UpdateAStateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateAStateRequest {
    return new UpdateAStateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateAStateRequest {
    return new UpdateAStateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateAStateRequest | PlainMessage<UpdateAStateRequest> | undefined, b: UpdateAStateRequest | PlainMessage<UpdateAStateRequest> | undefined): boolean {
    return proto3.util.equals(UpdateAStateRequest, a, b);
  }
}

/**
 * @generated from message reactive.v1.UpdateBStateResponse
 */
export class UpdateBStateResponse extends Message<UpdateBStateResponse> {
  /**
   * @generated from field: string b_state = 1;
   */
  bState = "";

  constructor(data?: PartialMessage<UpdateBStateResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "reactive.v1.UpdateBStateResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "b_state", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateBStateResponse {
    return new UpdateBStateResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateBStateResponse {
    return new UpdateBStateResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateBStateResponse {
    return new UpdateBStateResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateBStateResponse | PlainMessage<UpdateBStateResponse> | undefined, b: UpdateBStateResponse | PlainMessage<UpdateBStateResponse> | undefined): boolean {
    return proto3.util.equals(UpdateBStateResponse, a, b);
  }
}

/**
 * @generated from message reactive.v1.UpdateCStateResponse
 */
export class UpdateCStateResponse extends Message<UpdateCStateResponse> {
  /**
   * @generated from field: string c_state = 1;
   */
  cState = "";

  constructor(data?: PartialMessage<UpdateCStateResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "reactive.v1.UpdateCStateResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "c_state", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateCStateResponse {
    return new UpdateCStateResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateCStateResponse {
    return new UpdateCStateResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateCStateResponse {
    return new UpdateCStateResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateCStateResponse | PlainMessage<UpdateCStateResponse> | undefined, b: UpdateCStateResponse | PlainMessage<UpdateCStateResponse> | undefined): boolean {
    return proto3.util.equals(UpdateCStateResponse, a, b);
  }
}

